import uuid
from django.db import models
from pgvector.django import VectorField
from core.models import Vault
from vaults.models import Memory

class Person(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    vault = models.ForeignKey(Vault, on_delete=models.CASCADE, related_name='people')
    name = models.CharField(max_length=255)
    role = models.CharField(max_length=100, blank=True) # e.g., 'Patriarch', 'Son'
    birth_year = models.CharField(max_length=4, blank=True)
    death_year = models.CharField(max_length=4, null=True, blank=True)
    avatar_url = models.URLField(blank=True)
    biography = models.TextField(blank=True) # Generated by Story Weaver AI

class PersonFaceEmbedding(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='face_embeddings')
    memory = models.ForeignKey(Memory, on_delete=models.CASCADE, related_name='detected_faces')
    bounding_box = models.JSONField() # [top, right, bottom, left]
    embedding_vector = VectorField(dimensions=128) # dlib/face_recognition uses 128D vectors

class KinshipEdge(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    vault = models.ForeignKey(Vault, on_delete=models.CASCADE, related_name='kinship_edges')
    from_person = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='outgoing_edges')
    to_person = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='incoming_edges')
    relationship_type = models.CharField(max_length=50) # 'SPOUSE', 'CHILD', etc.