# Generated by Django 5.2.14 on 2026-05-16 10:40

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('vaults', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('birth_year', models.CharField(blank=True, max_length=4)),
                ('death_year', models.CharField(blank=True, max_length=4, null=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('biography', models.TextField(blank=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='core.vault')),
            ],
        ),
        migrations.CreateModel(
            name='KinshipEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(max_length=50)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinship_edges', to='core.vault')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='lineage.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='lineage.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonFaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bounding_box', models.JSONField()),
                ('embedding_vector', pgvector.django.vector.VectorField(dimensions=128)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_faces', to='vaults.memory')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='lineage.person')),
            ],
        ),
    ]
