# Generated by Django 5.2.14 on 2026-05-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active_story_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
