# Generated by Django 5.2.14 on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineage", "0002_person_active_story_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]

