# Generated by Django 6.0.2 on 2026-02-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inappnotification',
            new_name='notificatio_recipie_09c645_idx',
            old_name='notif_recipient_created_idx',
        ),
        migrations.RenameIndex(
            model_name='inappnotification',
            new_name='notificatio_recipie_4a51a1_idx',
            old_name='notif_recipient_read_idx',
        ),
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='notificatio_user_id_1159a5_idx',
            old_name='notif_push_user_active_idx',
        ),
    ]
