# Generated by Django 5.2.14 on 2026-05-16 10:40

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.ImageField(upload_to='vaults/originals/')),
                ('restored_file', models.ImageField(blank=True, null=True, upload_to='vaults/restored/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('cluster_name', models.CharField(default='Unsorted', max_length=100)),
                ('ai_caption', models.TextField(blank=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('clip_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True)),
                ('phash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='core.vault')),
            ],
        ),
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('unlock_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('READY', 'Ready'), ('OPENED', 'Opened')], default='LOCKED', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sealed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsules', to='core.vault')),
                ('memories', models.ManyToManyField(blank=True, related_name='capsules', to='vaults.memory')),
            ],
        ),
    ]
