# Generated by Django 5.2.14 on 2026-05-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='exif_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='memory',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
