# Generated by Django 6.0.2 on 2026-02-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('CONTRIBUTOR', 'Contributor'), ('VIEWER', 'Viewer')], default='CONTRIBUTOR', max_length=20),
        ),
    ]
