# Generated by Django 6.0.2 on 2026-02-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0002_alter_invite_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyvault',
            name='family_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]

