# Generated by Django 6.0.2 on 2026-02-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0004_familyvault_storage_quality_default_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='invite_type',
            field=models.CharField(
                choices=[('EMAIL', 'Email Invite'), ('SHAREABLE', 'Shareable Link')],
                default='EMAIL',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='invite',
            name='successful_joins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
