import { CircleNotch, MagicWand, TreeStructure, LockKey, MagnifyingGlass, CaretDown } from '@phosphor-icons/react';
import { motion, AnimatePresence } from 'framer-motion';
import { useState } from 'react';

const CATEGORIES = [
  { id: 'ai', icon: <MagicWand />, title: 'AI & Restoration', desc: 'Reviving old photos and managing auto-captions.', content: 'Our AI uses generative adversarial networks (GANs) to fill in missing pixels in scanned photos. Auto-captions are generated by analyzing visual context and matching them against your family tree metadata.' },
  { id: 'tree', icon: <TreeStructure />, title: 'Lineage Mapping', desc: 'Building connections and linking spousal vaults.', content: 'Add nodes by clicking "Graft Branch". To link with a spouse, use the "Lineage Pact" in the Governance section. This creates a virtual bridge between two distinct family vaults.' },
  { id: 'privacy', icon: <LockKey />, title: 'Privacy & Security', desc: 'Managing time capsules and vault governance.', content: 'Time capsules use AES-256 encryption. They remain unreadable even to our system administrators until the unlock date is reached. Vaults are "Zero-Knowledge" by default.' },
  { id: 'search', icon: <MagnifyingGlass />, title: 'Semantic Search', desc: 'Master the art of "Vibe" searching.', content: 'Instead of searching for filenames, describe the atmosphere. "Sunday morning coffee" will find artifacts matching that emotional tone using CLIP-based vector embeddings.' },
];

export default function Help() {
  const [activeId, setActiveId] = useState<string | null>(null);
  return (
    <div className="min-h-screen zone-light py-20 px-[clamp(24px,5vw,80px)]">
      <div className="max-w-[var(--max-width)] mx-auto">
        {/* Hero */}
        <header className="text-center mb-20">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-[var(--clr-gold-muted)] border border-[rgba(184,143,91,0.3)] rounded-full text-[var(--clr-gold-dark)] font-bold text-[10px] uppercase tracking-widest mb-6">
            <CircleNotch size={14} weight="fill" /> Knowledge Base
          </div>
          <h1 className="font-display text-[3rem] uppercase tracking-tight text-[var(--clr-ink)]">Museum Guidebook</h1>
          <p className="font-script text-[48px] text-[var(--clr-dust)] leading-[0.5] mt-4">"Mastering your family archive"</p>
        </header>

        {/* Categories Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {CATEGORIES.map((cat) => (
            <div key={cat.id} className="flex flex-col">
              <motion.button
                onClick={() => setActiveId(activeId === cat.id ? null : cat.id)}
                whileHover={{ y: -8 }}
                className={`p-8 bg-[var(--clr-linen)] border rounded-[var(--radius-lg)] text-left group transition-all h-full ${activeId === cat.id ? 'border-[var(--clr-gold)] ring-2 ring-[var(--clr-gold-muted)]' : 'border-[var(--clr-aged)]'}`}
              >
                <div className={`w-12 h-12 rounded-2xl flex items-center justify-center text-2xl mb-6 transition-colors ${activeId === cat.id ? 'bg-[var(--clr-gold)] text-white' : 'bg-[var(--clr-paper)] text-[var(--clr-gold)] group-hover:bg-[var(--clr-gold)] group-hover:text-white'}`}>
                  {cat.icon}
                </div>
                <h3 className="font-display font-semibold text-[1.25rem] text-[var(--clr-ink)] mb-2 flex items-center justify-between">
                  {cat.title}
                  <CaretDown size={16} className={`transition-transform ${activeId === cat.id ? 'rotate-180' : ''}`} />
                </h3>
                <p className="font-ui text-[13px] text-[var(--clr-dust)] leading-relaxed">{cat.desc}</p>

                <AnimatePresence>
                  {activeId === cat.id && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }}
                      className="overflow-hidden"
                    >
                      <p className="pt-6 mt-6 border-t border-[var(--clr-aged)] font-ui text-[12px] text-[var(--clr-ink)] leading-relaxed italic">
                        {cat.content}
                      </p>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.button>
            </div>
          ))}
        </div>

        {/* FAQ Section */}
        <div className="mt-32 max-w-3xl mx-auto space-y-12">
          <h2 className="font-display text-2xl text-center uppercase tracking-widest text-[var(--clr-ink)] border-b border-[var(--clr-aged)] pb-6">Common Curations</h2>
          {[
            { q: "Is my data really private?", a: "Yes. LegacyKeeper is built on zero-knowledge principles for family vaults. We do not sell data to advertisers." },
            { q: "How does the spousal linking work?", a: "When you link with another vault, we create a 'Lineage Pact'. Both trees grow together in the interface, but file ownership stays with the original vault." },
            { q: "What is a 'Vibe' search?", a: "Instead of searching for file names, you describe the scene. Our AI uses CLIP-based vector embeddings to find visual matches." }
          ].map((item, i) => (
            <div key={i} className="space-y-3">
              <h4 className="font-display font-bold text-lg text-[var(--clr-gold-dark)] italic">Q: {item.q}</h4>
              <p className="font-ui text-[15px] text-[var(--clr-ink)] leading-relaxed border-l-2 border-[var(--clr-gold-muted)] pl-6">{item.a}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}