# Generated by Django 6.0.2 on 2026-02-15 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_mediaitem_content_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='media.mediaitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='media_media_user_id_640a50_idx'), models.Index(fields=['media_item', 'user'], name='media_media_media_i_39e086_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'media_item'), name='uniq_user_media_favorite')],
            },
        ),
    ]
