# Generated by Django 6.0.2 on 2026-02-21 00:00

import core.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_mediafavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=core.utils.PathAndRename())),
                ('file_size', models.BigIntegerField(default=0, editable=False)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('file_type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('DOCUMENT', 'Document')], default='DOCUMENT', max_length=20)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='media.mediaitem')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
