# Generated by Django 6.0.2 on 2026-02-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('PARENT_OF', 'Parent Of'), ('ADOPTIVE_PARENT_OF', 'Adoptive Parent Of'), ('SPOUSE_OF', 'Spouse Of'), ('SIBLING_OF', 'Sibling Of')], max_length=20),
        ),
    ]
